version: "3.9"

services:
  mongodb-e3:
    image: mongo:latest
    container_name: mongodb-e3
    ports:
      - "27018:27017"
    networks:
      - mynetwork

  cart-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cart-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb-e3
    networks:
      - mynetwork

networks:
  mynetwork: